window.HADAF_SEED = {
  "classes": [
    {
      "id": "c1",
      "branch": "شعبه مرکزی",
      "category": "جنرال انگلیسی (General English)",
      "name": "جنرال انگلیسی - سطح مبتدی",
      "teacherId": "t1",
      "mode": "حضوری",
      "startDate": "2026-08-01",
      "endDate": "2026-08-31",
      "capacity": 15,
      "progress": 20,
      "location": "اتاق ۱",
      "note": "",
      "startTime": "06:00",
      "endTime": "07:00"
    },
    {
      "id": "c2",
      "branch": "شعبه مرکزی",
      "category": "آیلتس (IELTS)",
      "name": "آیلتس فشرده - صبح",
      "teacherId": "t4",
      "mode": "حضوری",
      "startDate": "2026-08-02",
      "endDate": "2026-09-01",
      "capacity": 12,
      "progress": 15,
      "location": "اتاق ۲",
      "note": "",
      "startTime": "07:00",
      "endTime": "08:30"
    },
    {
      "id": "c3",
      "branch": "شعبه مرکزی",
      "category": "کودکان و نوجوانان (Kids/Teens)",
      "name": "صنف کودکان - سطح یک",
      "teacherId": "t3",
      "mode": "حضوری",
      "startDate": "2026-07-01",
      "endDate": "2026-07-31",
      "capacity": 18,
      "progress": 100,
      "location": "اتاق ۳",
      "note": "دورهٔ تابستانی به پایان رسید",
      "startTime": "15:00",
      "endTime": "16:00"
    },
    {
      "id": "c4",
      "branch": "شعبه مرکزی",
      "category": "مکالمه (Conversation)",
      "name": "مکالمه پیشرفته",
      "teacherId": "t6",
      "mode": "حضوری",
      "startDate": "2026-09-05",
      "endDate": "2026-10-04",
      "capacity": 14,
      "progress": 0,
      "location": "اتاق ۱",
      "note": "",
      "startTime": "17:00",
      "endTime": "18:30"
    },
    {
      "id": "c5",
      "branch": "شعبه ۲",
      "category": "جنرال انگلیسی (General English)",
      "name": "جنرال انگلیسی - سطح متوسط",
      "teacherId": "t1",
      "mode": "حضوری",
      "startDate": "2026-08-01",
      "endDate": "2026-08-31",
      "capacity": 16,
      "progress": 18,
      "location": "اتاق ۱",
      "note": "",
      "startTime": "08:00",
      "endTime": "09:00"
    },
    {
      "id": "c6",
      "branch": "شعبه ۲",
      "category": "تافل (TOEFL)",
      "name": "تافل فشرده",
      "teacherId": "t2",
      "mode": "آنلاین",
      "startDate": "2026-08-03",
      "endDate": "2026-09-02",
      "capacity": 10,
      "progress": 12,
      "location": "",
      "note": "",
      "startTime": "18:00",
      "endTime": "19:30"
    },
    {
      "id": "c7",
      "branch": "شعبه ۲",
      "category": "کودکان و نوجوانان (Kids/Teens)",
      "name": "صنف کودکان - سطح دو",
      "teacherId": "t3",
      "mode": "حضوری",
      "startDate": "2026-06-10",
      "endDate": "2026-07-10",
      "capacity": 15,
      "progress": 100,
      "location": "اتاق ۲",
      "note": "",
      "startTime": "15:30",
      "endTime": "16:30"
    },
    {
      "id": "c8",
      "branch": "شعبه ۲",
      "category": "آیلتس (IELTS)",
      "name": "آیلتس - عصر",
      "teacherId": "t4",
      "mode": "حضوری",
      "startDate": "2026-07-15",
      "endDate": "2026-08-14",
      "capacity": 12,
      "progress": 78,
      "location": "اتاق ۳",
      "note": "",
      "startTime": "17:00",
      "endTime": "18:30"
    },
    {
      "id": "c9",
      "branch": "شعبه ۳",
      "category": "جنرال انگلیسی (General English)",
      "name": "جنرال انگلیسی - سطح پیشرفته",
      "teacherId": "t5",
      "mode": "حضوری",
      "startDate": "2026-08-01",
      "endDate": "2026-08-31",
      "capacity": 14,
      "progress": 22,
      "location": "اتاق ۱",
      "note": "",
      "startTime": "06:30",
      "endTime": "07:30"
    },
    {
      "id": "c10",
      "branch": "شعبه ۳",
      "category": "مکالمه (Conversation)",
      "name": "مکالمه - مبتدی",
      "teacherId": "t6",
      "mode": "حضوری",
      "startDate": "2026-08-04",
      "endDate": "2026-09-03",
      "capacity": 12,
      "progress": 5,
      "location": "اتاق ۲",
      "note": "",
      "startTime": "16:00",
      "endTime": "17:00"
    },
    {
      "id": "c11",
      "branch": "شعبه ۳",
      "category": "کودکان و نوجوانان (Kids/Teens)",
      "name": "صنف کودکان - تابستانی",
      "teacherId": "t3",
      "mode": "حضوری",
      "startDate": "2026-07-01",
      "endDate": "2026-07-31",
      "capacity": 20,
      "progress": 100,
      "location": "اتاق ۳",
      "note": "",
      "startTime": "15:00",
      "endTime": "16:00"
    },
    {
      "id": "c12",
      "branch": "شعبه ۳",
      "category": "آیلتس (IELTS)",
      "name": "آیلتس - فشردهٔ ویژه",
      "teacherId": "t4",
      "mode": "حضوری",
      "startDate": "2026-09-10",
      "endDate": "2026-10-09",
      "capacity": 10,
      "progress": 0,
      "location": "اتاق ۱",
      "note": "",
      "startTime": "07:00",
      "endTime": "08:30"
    }
  ],
  "studentProfiles": [
    {
      "id": "p1",
      "code": "S1405050001",
      "name": "عبدالله رحیمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0788001122",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-28",
      "familyId": "یعقوبی"
    },
    {
      "id": "p2",
      "code": "S1405050002",
      "name": "مریم حسینی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700112233",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-29",
      "familyId": "یعقوبی"
    },
    {
      "id": "p3",
      "code": "S1405050003",
      "name": "ذبیح‌الله نجفی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0777223344",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-30",
      "familyId": "یعقوبی"
    },
    {
      "id": "p4",
      "code": "S1405050004",
      "name": "نگار سلطانی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0793334455",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-01",
      "familyId": ""
    },
    {
      "id": "p5",
      "code": "S1405050005",
      "name": "فرید احمدی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0744445566",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-25",
      "familyId": ""
    },
    {
      "id": "p6",
      "code": "S1405050006",
      "name": "حمیرا قاسمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0766556677",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-27",
      "familyId": ""
    },
    {
      "id": "p7",
      "code": "S1405050007",
      "name": "عمر سروری",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700667788",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-30",
      "familyId": ""
    },
    {
      "id": "p8",
      "code": "S1405040001",
      "name": "یاسین مرادی",
      "grade": "۹ ساله",
      "guardianName": "محمد نعیم مرادی",
      "guardianPhone": "0788778899",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-28",
      "familyId": ""
    },
    {
      "id": "p9",
      "code": "S1405040002",
      "name": "تمنا نوری",
      "grade": "۸ ساله",
      "guardianName": "عبدالرحمن نوری",
      "guardianPhone": "0700889900",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-29",
      "familyId": ""
    },
    {
      "id": "p10",
      "code": "S1405040003",
      "name": "سهراب بارکزی",
      "grade": "۱۰ ساله",
      "guardianName": "حارث بارکزی",
      "guardianPhone": "0777990011",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-30",
      "familyId": ""
    },
    {
      "id": "p11",
      "code": "S1405050008",
      "name": "زهرا عثمانی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0793001122",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-02",
      "familyId": ""
    },
    {
      "id": "p12",
      "code": "S1405050009",
      "name": "آرش رستمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0744112233",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-03",
      "familyId": ""
    },
    {
      "id": "p13",
      "code": "S1405050010",
      "name": "شکیب صافی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0766223344",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-27",
      "familyId": ""
    },
    {
      "id": "p14",
      "code": "S1405050011",
      "name": "لیلا احمدی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700334455",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-28",
      "familyId": ""
    },
    {
      "id": "p15",
      "code": "S1405050012",
      "name": "نوید حسینی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0788445566",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-29",
      "familyId": ""
    },
    {
      "id": "p16",
      "code": "S1405050013",
      "name": "وسیمه کریمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0793556677",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-31",
      "familyId": ""
    },
    {
      "id": "p17",
      "code": "S1405050014",
      "name": "عبدالله سلطانی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700667700",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-26",
      "familyId": ""
    },
    {
      "id": "p18",
      "code": "S1405050015",
      "name": "فاطمه نجفی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0777778899",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-30",
      "familyId": ""
    },
    {
      "id": "p19",
      "code": "S1405030001",
      "name": "حدیثه بارکزی",
      "grade": "۷ ساله",
      "guardianName": "ذبیح‌الله بارکزی",
      "guardianPhone": "0744889900",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-05-28",
      "familyId": ""
    },
    {
      "id": "p20",
      "code": "S1405030002",
      "name": "آرزو مرادی",
      "grade": "۹ ساله",
      "guardianName": "شکیب مرادی",
      "guardianPhone": "0766990011",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-05-29",
      "familyId": ""
    },
    {
      "id": "p21",
      "code": "S1405030003",
      "name": "محمد نعیم قاسمی",
      "grade": "۱۱ ساله",
      "guardianName": "فرید قاسمی",
      "guardianPhone": "0788001100",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-01",
      "familyId": ""
    },
    {
      "id": "p22",
      "code": "S1405040004",
      "name": "نیلوفر سروری",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0793112200",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-13",
      "familyId": ""
    },
    {
      "id": "p23",
      "code": "S1405040005",
      "name": "بلال احمدی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700223311",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-14",
      "familyId": ""
    },
    {
      "id": "p24",
      "code": "S1405040006",
      "name": "مریم رستمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0777334422",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-15",
      "familyId": ""
    },
    {
      "id": "p25",
      "code": "S1405050016",
      "name": "حارث یعقوبی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0744445500",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-29",
      "familyId": ""
    },
    {
      "id": "p26",
      "code": "S1405050017",
      "name": "زهرا صافی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0766556611",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-07-30",
      "familyId": ""
    },
    {
      "id": "p27",
      "code": "S1405050018",
      "name": "عمر نوری",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0788667722",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-01",
      "familyId": ""
    },
    {
      "id": "p28",
      "code": "S1405050019",
      "name": "شبنم عثمانی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0793778833",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-02",
      "familyId": ""
    },
    {
      "id": "p29",
      "code": "S1405050020",
      "name": "ولی رحیمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0700889944",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-03",
      "familyId": ""
    },
    {
      "id": "p30",
      "code": "S1405040007",
      "name": "تمنا حسینی",
      "grade": "۸ ساله",
      "guardianName": "عمر حسینی",
      "guardianPhone": "0777990055",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-27",
      "familyId": ""
    },
    {
      "id": "p31",
      "code": "S1405040008",
      "name": "یاسین سلطانی",
      "grade": "۱۰ ساله",
      "guardianName": "بلال سلطانی",
      "guardianPhone": "0744001166",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-06-28",
      "familyId": ""
    },
    {
      "id": "p32",
      "code": "S1405050021",
      "name": "نگار قاسمی",
      "grade": "",
      "guardianName": "خودش",
      "guardianPhone": "0766112277",
      "photo": "",
      "idPhoto": "",
      "note": "",
      "createdAt": "2026-08-01",
      "familyId": ""
    }
  ],
  "students": [
    {
      "id": "s1",
      "profileId": "p1",
      "classId": "c1",
      "registerDate": "2026-07-28",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 3500,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 5,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s2",
      "profileId": "p2",
      "classId": "c1",
      "registerDate": "2026-07-29",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 1750,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s3",
      "profileId": "p3",
      "classId": "c1",
      "registerDate": "2026-07-30",
      "feeAmount": 3500,
      "discountPercent": 10,
      "paidAmount": 3150,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 25,
      "referredBy": ""
    },
    {
      "id": "s4",
      "profileId": "p4",
      "classId": "c1",
      "registerDate": "2026-08-01",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s5",
      "profileId": "p5",
      "classId": "c2",
      "registerDate": "2026-07-25",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 5000,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 10,
      "familyDiscountPercent": 0,
      "referredBy": "p1"
    },
    {
      "id": "s6",
      "profileId": "p6",
      "classId": "c2",
      "registerDate": "2026-07-27",
      "feeAmount": 5000,
      "discountPercent": 15,
      "paidAmount": 4250,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s7",
      "profileId": "p7",
      "classId": "c2",
      "registerDate": "2026-07-30",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s8",
      "profileId": "p8",
      "classId": "c3",
      "registerDate": "2026-06-28",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 92,
      "examScore": 75,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s9",
      "profileId": "p9",
      "classId": "c3",
      "registerDate": "2026-06-29",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 78,
      "examScore": 84,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s10",
      "profileId": "p10",
      "classId": "c3",
      "registerDate": "2026-06-30",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 1250,
      "result": "ناکام",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 45,
      "examScore": 40,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s11",
      "profileId": "p11",
      "classId": "c4",
      "registerDate": "2026-08-02",
      "feeAmount": 3000,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s12",
      "profileId": "p12",
      "classId": "c4",
      "registerDate": "2026-08-03",
      "feeAmount": 3000,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s13",
      "profileId": "p13",
      "classId": "c5",
      "registerDate": "2026-07-27",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 3500,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s14",
      "profileId": "p14",
      "classId": "c5",
      "registerDate": "2026-07-28",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 3500,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s15",
      "profileId": "p15",
      "classId": "c5",
      "registerDate": "2026-07-29",
      "feeAmount": 3500,
      "discountPercent": 20,
      "paidAmount": 1400,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s16",
      "profileId": "p16",
      "classId": "c5",
      "registerDate": "2026-07-31",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s17",
      "profileId": "p17",
      "classId": "c6",
      "registerDate": "2026-07-26",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 5000,
      "result": "",
      "note": "",
      "bookTitle": "TOEFL iBT Prep Book",
      "bookPrice": 550,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s18",
      "profileId": "p18",
      "classId": "c6",
      "registerDate": "2026-07-30",
      "feeAmount": 5000,
      "discountPercent": 10,
      "paidAmount": 2250,
      "result": "",
      "note": "",
      "bookTitle": "TOEFL iBT Prep Book",
      "bookPrice": 550,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s19",
      "profileId": "p19",
      "classId": "c7",
      "registerDate": "2026-05-28",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 82,
      "examScore": 75,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s20",
      "profileId": "p20",
      "classId": "c7",
      "registerDate": "2026-05-29",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 92,
      "examScore": 90,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s21",
      "profileId": "p21",
      "classId": "c7",
      "registerDate": "2026-06-01",
      "feeAmount": 0,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": 78,
      "examScore": 90,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s22",
      "profileId": "p22",
      "classId": "c8",
      "registerDate": "2026-07-13",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 5000,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s23",
      "profileId": "p23",
      "classId": "c8",
      "registerDate": "2026-07-14",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 5000,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s24",
      "profileId": "p24",
      "classId": "c8",
      "registerDate": "2026-07-15",
      "feeAmount": 5000,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s25",
      "profileId": "p25",
      "classId": "c9",
      "registerDate": "2026-07-29",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 3500,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s26",
      "profileId": "p26",
      "classId": "c9",
      "registerDate": "2026-07-30",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 3500,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s27",
      "profileId": "p27",
      "classId": "c9",
      "registerDate": "2026-08-01",
      "feeAmount": 3500,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s28",
      "profileId": "p28",
      "classId": "c10",
      "registerDate": "2026-08-02",
      "feeAmount": 3000,
      "discountPercent": 0,
      "paidAmount": 3000,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s29",
      "profileId": "p29",
      "classId": "c10",
      "registerDate": "2026-08-03",
      "feeAmount": 3000,
      "discountPercent": 0,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "General English Coursebook 1",
      "bookPrice": 350,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s30",
      "profileId": "p30",
      "classId": "c11",
      "registerDate": "2026-06-27",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 2500,
      "result": "کامیاب",
      "note": "",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 90,
      "examScore": 75,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s31",
      "profileId": "p31",
      "classId": "c11",
      "registerDate": "2026-06-28",
      "feeAmount": 2500,
      "discountPercent": 0,
      "paidAmount": 1250,
      "result": "کامیاب مشروط",
      "note": "نیازمند امتحان مجدد (ری‌تیک) در مبحث دستور زبان",
      "bookTitle": "Kids English Starter",
      "bookPrice": 250,
      "bookPaid": true,
      "idCardPrice": 150,
      "idCardPaid": true,
      "activityScore": 45,
      "examScore": 40,
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    },
    {
      "id": "s32",
      "profileId": "p32",
      "classId": "c12",
      "registerDate": "2026-08-01",
      "feeAmount": 5000,
      "discountPercent": 5,
      "paidAmount": 0,
      "result": "",
      "note": "",
      "bookTitle": "IELTS Cambridge Practice Tests",
      "bookPrice": 600,
      "bookPaid": false,
      "idCardPrice": 150,
      "idCardPaid": false,
      "activityScore": "",
      "examScore": "",
      "referralDiscountPercent": 0,
      "familyDiscountPercent": 0,
      "referredBy": ""
    }
  ],
  "teachers": [
    {
      "id": "t1",
      "name": "استاد احمد ولی رحیمی",
      "phone": "0788112233",
      "subjects": "جنرال انگلیسی، آیلتس",
      "role": "مدرس",
      "payType": "به ازای هر صنف (ماهانه)",
      "payAmount": 4500,
      "note": "",
      "createdAt": "2025-09-01",
      "contractStart": "2025-09-01",
      "contractEnd": "",
      "code": "T1404060001",
      "photo": "",
      "idPhoto": "",
      "password": "782554"
    },
    {
      "id": "t2",
      "name": "استاد مرسل نظری",
      "phone": "0700456789",
      "subjects": "تافل، مکالمه",
      "role": "مدرس",
      "payType": "به ازای هر صنف (ماهانه)",
      "payAmount": 4800,
      "note": "",
      "createdAt": "2025-10-15",
      "contractStart": "2025-10-15",
      "contractEnd": "",
      "code": "T1404070001",
      "photo": "",
      "idPhoto": "",
      "password": "150631"
    },
    {
      "id": "t3",
      "name": "استاده فرشته یعقوبی",
      "phone": "0777998877",
      "subjects": "صنف کودکان و نوجوانان",
      "role": "مدرس",
      "payType": "به ازای هر صنف (ماهانه)",
      "payAmount": 3800,
      "note": "",
      "createdAt": "2025-11-01",
      "contractStart": "2025-11-01",
      "contractEnd": "",
      "code": "T1404080001",
      "photo": "",
      "idPhoto": "",
      "password": "175954"
    },
    {
      "id": "t4",
      "name": "استاد جاوید کریمی",
      "phone": "0793221144",
      "subjects": "آیلتس",
      "role": "مدرس",
      "payType": "به ازای هر صنف (ماهانه)",
      "payAmount": 5000,
      "note": "",
      "createdAt": "2026-01-10",
      "contractStart": "2026-01-10",
      "contractEnd": "",
      "code": "T1404100001",
      "photo": "",
      "idPhoto": "",
      "password": "961168"
    },
    {
      "id": "t5",
      "name": "استاده سحر امینی",
      "phone": "0744556677",
      "subjects": "جنرال انگلیسی",
      "role": "مدیریت",
      "payType": "ماهانه ثابت",
      "payAmount": 15000,
      "note": "مسئول ارشد صنوف جنرال انگلیسی",
      "createdAt": "2025-08-01",
      "contractStart": "2025-08-01",
      "contractEnd": "",
      "code": "M1404050001",
      "photo": "",
      "idPhoto": "",
      "password": "661913"
    },
    {
      "id": "t6",
      "name": "استاد بلال ستانکزی",
      "phone": "0766334455",
      "subjects": "مکالمه، صنف کودکان",
      "role": "مدرس",
      "payType": "به ازای هر صنف (ماهانه)",
      "payAmount": 4000,
      "note": "",
      "createdAt": "2026-02-01",
      "contractStart": "2026-02-01",
      "contractEnd": "",
      "code": "T1404110001",
      "photo": "",
      "idPhoto": "",
      "password": "198702"
    },
    {
      "id": "t7",
      "name": "علی محمدی",
      "phone": "0788990011",
      "subjects": "",
      "role": "کارمند",
      "payType": "ماهانه ثابت",
      "payAmount": 10000,
      "note": "مسئول پذیرش و امور اداری",
      "createdAt": "2025-09-15",
      "contractStart": "2025-09-15",
      "contractEnd": "",
      "code": "E1404060001",
      "photo": "",
      "idPhoto": "",
      "password": "483452"
    }
  ],
  "donations": [
    {
      "id": "d2",
      "donorName": "هزینهٔ صدور گواهی‌نامه",
      "amount": 3500,
      "discountPercent": 0,
      "method": "کارت به کارت",
      "date": "2026-07-28",
      "note": ""
    },
    {
      "id": "d3",
      "donorName": "آزمون تعیین سطح",
      "amount": 500,
      "discountPercent": 0,
      "method": "نقدی",
      "date": "2026-08-01",
      "note": "برای متقاضیان جدید"
    },
    {
      "id": "d4",
      "donorName": "فروش کتاب آیلتس کمبریج",
      "amount": 8000,
      "discountPercent": 10,
      "method": "نقدی",
      "date": "2026-07-15",
      "note": ""
    },
    {
      "id": "d5",
      "donorName": "حمایت مالی برای سمینار",
      "amount": 5000,
      "discountPercent": 0,
      "method": "آنلاین",
      "date": "2026-08-05",
      "note": ""
    },
    {
      "id": "d6",
      "donorName": "سایر",
      "amount": 1200,
      "discountPercent": 0,
      "method": "سایر",
      "date": "2026-06-20",
      "note": ""
    }
  ],
  "expenses": [
    {
      "id": "e1",
      "branch": "شعبه مرکزی",
      "category": "اجارهٔ شعبه",
      "amount": 25000,
      "date": "2026-08-01",
      "note": "اجارهٔ ماه اگست"
    },
    {
      "id": "e2",
      "branch": "شعبه ۲",
      "category": "اجارهٔ شعبه",
      "amount": 20000,
      "date": "2026-08-01",
      "note": "اجارهٔ ماه اگست"
    },
    {
      "id": "e3",
      "branch": "شعبه ۳",
      "category": "اجارهٔ شعبه",
      "amount": 18000,
      "date": "2026-08-01",
      "note": "اجارهٔ ماه اگست"
    },
    {
      "id": "e4",
      "branch": "شعبه مرکزی",
      "category": "قبض و خدمات (برق/آب/گاز/اینترنت)",
      "amount": 4200,
      "date": "2026-08-02",
      "note": ""
    },
    {
      "id": "e5",
      "branch": "شعبه ۲",
      "category": "قبض و خدمات (برق/آب/گاز/اینترنت)",
      "amount": 3600,
      "date": "2026-08-02",
      "note": ""
    },
    {
      "id": "e6",
      "branch": "شعبه ۳",
      "category": "قبض و خدمات (برق/آب/گاز/اینترنت)",
      "amount": 3100,
      "date": "2026-08-02",
      "note": ""
    },
    {
      "id": "e7",
      "branch": "شعبه مرکزی",
      "category": "لوازم آموزشی",
      "amount": 6800,
      "date": "2026-07-20",
      "note": "خرید وایت‌بورد و مارکر"
    },
    {
      "id": "e8",
      "branch": "شعبه ۲",
      "category": "تبلیغات و بازاریابی",
      "amount": 5000,
      "date": "2026-07-25",
      "note": "تبلیغات در فیسبوک و اینستاگرام"
    },
    {
      "id": "e9",
      "branch": "شعبه ۳",
      "category": "پذیرایی",
      "amount": 1500,
      "date": "2026-08-03",
      "note": ""
    },
    {
      "id": "e10",
      "branch": "شعبه مرکزی",
      "category": "حقوق و دستمزد مدرسان",
      "amount": 8500,
      "date": "2026-07-05",
      "note": "قسط حقوق ماه گذشته"
    },
    {
      "id": "e11",
      "branch": "شعبه ۲",
      "category": "سایر",
      "amount": 2200,
      "date": "2026-07-18",
      "note": "تعمیر کولر"
    },
    {
      "id": "e12",
      "branch": "شعبه ۳",
      "category": "لوازم آموزشی",
      "amount": 4300,
      "date": "2026-08-01",
      "note": ""
    }
  ],
  "projects": [
    {
      "id": "p1",
      "name": "کمپین تبلیغاتی پاییزی",
      "category": "کمپین تبلیغاتی",
      "lead": "استاد مرسل نظری",
      "startDate": "2026-08-01",
      "endDate": "2026-09-15",
      "note": "تبلیغ در شبکه‌های اجتماعی و بروشور برای ثبت‌نام دورهٔ جدید",
      "progress": 30,
      "progressLog": []
    },
    {
      "id": "p2",
      "name": "مراسم فارغ‌التحصیلی دورهٔ تابستانی",
      "category": "مراسم فارغ‌التحصیلی",
      "lead": "استاد احمد ولی رحیمی",
      "startDate": "2026-08-15",
      "endDate": "2026-08-15",
      "note": "",
      "progress": 10,
      "progressLog": []
    },
    {
      "id": "p3",
      "name": "همکاری با دانشگاه خصوصی برای بورسیه",
      "category": "همکاری با نهاد دیگر",
      "lead": "استاد جاوید کریمی",
      "startDate": "2026-07-01",
      "endDate": "",
      "note": "",
      "progress": 60,
      "progressLog": []
    }
  ],
  "meetings": [
    {
      "id": "m1",
      "date": "2026-07-28",
      "attendees": "احمد ولی، مرسل، فرشته، جاوید",
      "notes": "بررسی ثبت‌نامی صنف‌های اگست و برنامه‌ریزی کمپین تبلیغاتی",
      "tasks": [
        {
          "id": "tk1",
          "text": "طراحی بروشور جدید",
          "assignee": "مرسل",
          "done": true
        },
        {
          "id": "tk2",
          "text": "هماهنگی با صفحهٔ اینستاگرام",
          "assignee": "جاوید",
          "done": false
        }
      ]
    },
    {
      "id": "m2",
      "date": "2026-08-04",
      "attendees": "همهٔ مدرسان",
      "notes": "گزارش پیشرفت صنف‌ها و بحث دربارهٔ سمینار آیلتس",
      "tasks": [
        {
          "id": "tk3",
          "text": "تهیهٔ لیست شرکت‌کنندگان سمینار",
          "assignee": "مرسل",
          "done": false
        },
        {
          "id": "tk4",
          "text": "چاپ گواهی‌نامه‌ها",
          "assignee": "احمد ولی",
          "done": false
        }
      ]
    },
    {
      "id": "m3",
      "date": "2026-07-14",
      "attendees": "مدیریت و مسئولین شعبه‌ها",
      "notes": "بررسی وضعیت مالی سه‌ماههٔ اخیر و مقایسهٔ شعبه‌ها",
      "tasks": [
        {
          "id": "tk5",
          "text": "جمع‌آوری گزارش هزینه‌های هر شعبه",
          "assignee": "سحر",
          "done": true
        }
      ]
    }
  ],
  "seminars": [
    {
      "id": "sm1",
      "title": "کارگاه آمادگی آزمون آیلتس",
      "type": "کارگاه",
      "mode": "حضوری",
      "location": "شعبه مرکزی",
      "speakerId": "t4",
      "date": "2026-07-25",
      "attendeeCount": 22,
      "isPaid": true,
      "fee": 800,
      "discountPercent": 0,
      "note": ""
    },
    {
      "id": "sm2",
      "title": "وبینار رازهای یادگیری سریع زبان",
      "type": "وبینار",
      "mode": "آنلاین",
      "location": "آنلاین",
      "speakerId": "t1",
      "date": "2026-08-10",
      "attendeeCount": 60,
      "isPaid": false,
      "fee": 0,
      "discountPercent": 0,
      "note": ""
    },
    {
      "id": "sm3",
      "title": "سمینار مسیر شغلی با مهارت زبان انگلیسی",
      "type": "سمینار",
      "mode": "حضوری",
      "location": "شعبه ۲",
      "speakerId": "t2",
      "date": "2026-08-20",
      "attendeeCount": 35,
      "isPaid": true,
      "fee": 500,
      "discountPercent": 20,
      "note": "تخفیف ثبت‌نام زودهنگام"
    },
    {
      "id": "sm4",
      "title": "کارگاه نویسندگی برای تافل",
      "type": "کارگاه",
      "mode": "حضوری",
      "location": "شعبه ۳",
      "speakerId": "t4",
      "date": "2026-09-15",
      "attendeeCount": 0,
      "isPaid": true,
      "fee": 1000,
      "discountPercent": 10,
      "note": ""
    },
    {
      "id": "sm5",
      "title": "کمپ تابستانی مکالمه برای نوجوانان",
      "type": "کارگاه",
      "mode": "حضوری",
      "location": "شعبه مرکزی",
      "speakerId": "t6",
      "date": "2026-07-10",
      "attendeeCount": 18,
      "isPaid": true,
      "fee": 600,
      "discountPercent": 0,
      "note": ""
    }
  ],
  "teacherAdvances": [
    {
      "id": "adv1",
      "teacherId": "t1",
      "amount": 3000,
      "date": "2026-08-01",
      "note": "پیش‌پرداخت درخواستی",
      "settled": false
    },
    {
      "id": "adv2",
      "teacherId": "t4",
      "amount": 2000,
      "date": "2026-07-20",
      "note": "پیش‌پرداخت ماه گذشته",
      "settled": true
    },
    {
      "id": "adv3",
      "teacherId": "t6",
      "amount": 1000,
      "date": "2026-08-02",
      "note": "",
      "settled": false
    }
  ],
  "shareholders": [
    {
      "id": "sh1",
      "code": "SH1405050001",
      "name": "Mohammad Hanif Mahdiyar",
      "sharePercent": 45,
      "phone": "0700111222",
      "photo": "",
      "idPhoto": "",
      "note": "بنیان‌گذار و سهامدار اصلی",
      "createdAt": "2026-08-06",
      "password": "439563"
    },
    {
      "id": "sh2",
      "code": "SH1405050002",
      "name": "Alireza Elham",
      "sharePercent": 45,
      "phone": "0700222333",
      "photo": "",
      "idPhoto": "",
      "note": "سهامدار و شریک راهبردی",
      "createdAt": "2026-08-06",
      "password": "258176"
    },
    {
      "id": "sh3",
      "code": "SH1405050003",
      "name": "Habibullah Kakar",
      "sharePercent": 10,
      "phone": "0700333444",
      "photo": "",
      "idPhoto": "",
      "note": "سهامدار",
      "createdAt": "2026-08-06",
      "password": "514002"
    }
  ],
  "bookPurchases": [
    {
      "id": "bp1",
      "title": "General English Coursebook 1",
      "source": "مطبعهٔ آریانا",
      "branch": "شعبه مرکزی",
      "quantity": 30,
      "unitCost": 250,
      "totalCost": 7500,
      "date": "2026-07-20",
      "note": "",
      "paidAmount": 7500,
      "paidDate": "2026-07-20",
      "dueDate": ""
    },
    {
      "id": "bp2",
      "title": "IELTS Cambridge Practice Tests",
      "source": "کتاب‌فروشی سعیدی",
      "branch": "شعبه ۲",
      "quantity": 20,
      "unitCost": 450,
      "totalCost": 9000,
      "date": "2026-07-22",
      "note": "",
      "paidAmount": 4500,
      "paidDate": "2026-07-22",
      "dueDate": "2026-08-20"
    },
    {
      "id": "bp3",
      "title": "Kids English Starter",
      "source": "مطبعهٔ آریانا",
      "branch": "شعبه ۳",
      "quantity": 25,
      "unitCost": 180,
      "totalCost": 4500,
      "date": "2026-07-25",
      "note": "",
      "paidAmount": 4500,
      "paidDate": "2026-07-25",
      "dueDate": ""
    },
    {
      "id": "bp4",
      "title": "TOEFL iBT Prep Book",
      "source": "کتاب‌فروشی سعیدی",
      "branch": "شعبه ۲",
      "quantity": 15,
      "unitCost": 400,
      "totalCost": 6000,
      "date": "2026-08-01",
      "note": "",
      "paidAmount": 0,
      "paidDate": "",
      "dueDate": "2026-08-15"
    }
  ],
  "attendance": [
    {
      "classId": "c1",
      "date": "2026-08-01",
      "marks": {
        "s1": true,
        "s2": true,
        "s3": true,
        "s4": false
      }
    },
    {
      "classId": "c1",
      "date": "2026-08-02",
      "marks": {
        "s1": true,
        "s2": true,
        "s3": false,
        "s4": true
      }
    },
    {
      "classId": "c1",
      "date": "2026-08-03",
      "marks": {
        "s1": true,
        "s2": false,
        "s3": true,
        "s4": true
      }
    },
    {
      "classId": "c1",
      "date": "2026-08-04",
      "marks": {
        "s1": true,
        "s2": true,
        "s3": true,
        "s4": true
      }
    }
  ]
};
